name: Prowlarr

on:
  workflow_dispatch:

jobs:
  start-prowlarr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Prowlarr
        run: |
         sudo adduser prowlarr
         sudo apt install curl sqlite3
         wget --content-disposition 'http://prowlarr.servarr.com/v1/update/develop/updatefile?os=linux&runtime=netcore&arch=x64'
         tar -xvzf Prowlarr*.linux*.tar.gz
         sudo mv Prowlarr/ /opt
         wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
         sudo dpkg -i cloudflared-linux-amd64.deb
         npm install -g localtunnel
         sudo /opt/Prowlarr/Prowlarr -nobrowser -data=/var/lib/prowlarr/ & lt --port 8000 --subdomain babyprowl
